version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: multiaddr
    versions:
    - 9.0.1
  - dependency-name: ipfs-utils
    versions:
    - 6.0.0
    - 6.0.1
    - 6.0.3
    - 6.0.4
    - 6.0.5
    - 6.0.6
  - dependency-name: aegir
    versions:
    - 30.3.0
    - 31.0.0
    - 31.0.1
    - 31.0.3
    - 31.0.4
    - 32.0.2
    - 32.1.0
    - 32.2.0
    - 33.0.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: ipfs-unixfs
    versions:
    - 3.0.0
    - 3.0.1
    - 4.0.0
    - 4.0.1
  - dependency-name: ipfs-http-client
    versions:
    - 49.0.0
    - 49.0.1
    - 49.0.2
    - 49.0.3
  - dependency-name: ipfs
    versions:
    - 0.53.2
    - 0.54.0
    - 0.54.1
    - 0.54.2
    - 0.54.3
  - dependency-name: go-ipfs
    versions:
    - 0.8.0
